const LOAD_GAME = "LOAD_GAME";
const START_GAME = "START_GAME";
const CELL_RIGHT_CLICK = "CELL_RIGHT_CLICK";
const CELL_CLICK = "CELL_CLICK";
const GAME_RESET = "GAME_RESET";
const SET_TIMER_ID = "SET_TIMER_ID";

module.exports = {
	LOAD_GAME,
	START_GAME,
	CELL_RIGHT_CLICK,
	CELL_CLICK,
	GAME_RESET,
	SET_TIMER_ID
}